<a href="https://colab.research.google.com/github/luisgoni/RepositorioCurso-ADA/blob/main/Exercicios_aula_mod4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercicios feito em aula...**

`np.zeros((3,4))` # Create an array of zeros  
`np.ones((2,3,4),dtype=np.int16)` # Create an array of ones  
`d = np.arange(10,25,5)` # Create an array of evenly spaced values(step value)  
`np.linspace(0,2,9)` # Create an array of evenly spaced values(number of samples)  
`e = np.full((2,2),7)` # Create a constant array  
`f = np.eye(2)` # Create a 2X2 identity matrix    
`np.identity(2)` # Create the identity array  
`np.random.random((2,2))` # Create an array with random values  
`np.empty((3,2)) ` # Create an empty array  

## Aula 02

In [1]:
import pandas as pd
import numpy as np


 - Exercicios :
1. Crie um array numpy com valores partindo de 10 até 49
2. Crie uma matriz numpy de 2 por 2 preenchida com 1's
3. Crie uma matriz numpy 3 por 2 de floats preenchida com 1's
4. Crie uma matriz 4 por 4 de integers preenchida com 5's
5. Crie uma matriz identidade de 3 por 3
6. Crie um array numppy prrenchido 3 integers aleatórias entre 1 e 10

In [10]:
# 1. Crie um array numpy com valores partindo de 10 até 49:
numeros = np.arange(10,49)
print(f'Numeros de 10 a 49 : {numeros}')

Numeros de 10 a 49 : [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [16]:
# 2. Crie uma matriz numpy de 2 por 2 preenchida com 1's:
matrizde1 = np.ones((2, 2))
print('\nMatriz de 2 por 2 de numero 1\n',matrizde1)


Matriz de 2 por 2 de numero 1
 [[1. 1.]
 [1. 1.]]


In [18]:
# 3.Crie uma matriz numpy 3 por 2 de floats preenchida com 1's
matriz2 = np.ones((3, 2), dtype=float)
print("\nMatriz de 3 por 2 de numeros floats\n", matriz2)


Matriz de 3 por 2 de numeros floats
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
# 4. Crie uma matriz 4 por 4 de integers preenchida com 5's
matriz = np.full((4, 4), 5)
print("\nMatriz de 4 por 4 com numero 5 inteiro\n", matriz)


Matriz de 4 por 4 com numero 5 inteiro
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [22]:
# 5. Crie uma matriz identidade de 3 por 3
matrizID = np.eye(3)
print("\nMatriz de identidade:\n", matrizID)


Matriz de identidade:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# 6. Crie um array numpy preenchido com 3 integers aleatórias entre 1 e 10
array = np.random.randint(1, 11, 3)
print("\nArray com 3 interiros aleatorios :\n", array)


Array com 3 interiros aleatorios :
 [3 3 2]


### Continuidade exercicios Aula 2
1. Dado o array X = np.array(['A','B','C','D','E'])
Mostre o último elemento
2. Mostre os primeiros 3 elementos
3. Mostre só os elementos do meio
4. Inverta a ordem do array
5. Mostre os elementos nas posições impar.
6. De acordo com a matriz, mostre a primeira linha X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
7. Mostre o primeiro elemento na primeira linha
8. Mostre a linha intermediária
9. Os primeiros 2 elementos das duas primeiras linhas
10. Os últimos 2 elementos das duas últimas linhas

In [41]:
#1 Dado o array X = np.array(['A','B','C','D','E']), Mostre o último elemnto.
x = (['A','B','C','D','E'])
print("\nMostrando o ultimo elemento: \n", x[-1])


Mostrando o ultimo elemento: 
 E


In [35]:
# 2 Mostre os primeiros 3 elementos:
print('\nMostrando os 3 primeiros elementos da lista:\n, ',x[:3])


Mostrando os 3 primeiros elementos da lista:
,  ['A', 'B', 'C']


In [39]:
#3 Mostre só os elemntos do meio:
print('\nMostrando os elementos do meio: \n',x[1:4])


Mostrando os elementos do meio: 
 ['B', 'C', 'D']


In [43]:
#4 Inverta a ordem do array:
print("\n Invertendo a ordem do array \n", x[::-1])


 Invertendo a ordem do array 
 ['E', 'D', 'C', 'B', 'A']


In [44]:
#5. Mostre os elementos nas posições impar.
print("\nMostrando os numeros impar:\n", x[::2])


Mostrando os numeros impar:
 ['A', 'C', 'E']


In [46]:
#6. De acordo com a matriz, mostre a primeira linha X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16] ]):
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
print("\n Mostrando a prijmeira linha: \n", X[0])



 Mostrando a prijmeira linha: 
 [1 2 3 4]


In [47]:
#7. Mostre o primeiro elemento na primeira linha:
print("\nMostrando o primeiro elemento na primeira linha\n", X[0, 0])


Mostrando o primeiro elemento na primeira linha
 1


In [48]:
#8. Mostre a linha intermediária
print("\nMostrando o intermediario:\n", X[X.shape[0]//2])


Mostrando o intermediario:
 [ 9 10 11 12]


In [49]:
#9. Os primeiros 2 elementos das duas primeiras linhas
print("\nResposta:\n", X[:2, :2])


Resposta:
 [[1 2]
 [5 6]]


In [51]:
#10. Os últimos 2 elementos das duas últimas linhas
print("\nResposta:\n", X[-2:, -2:])


Resposta:
 [[11 12]
 [15 16]]


##Parte 3
1. De acordo com o array X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
faça a soma
2. Faça a média
3. Dada a matriz faça a soma das colunas X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
4. Faça a média das linhas
5. Dado o array X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
Mostre o elemento de maior valor

In [ ]:
#1 De acordo com o array X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
x = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
soma = (x.sum())
print(soma)


43


In [ ]:
#2. Faça a Média:
Média = x.mean()
print('A média dos numeros são :',Média)

A média dos numeros são : 4.777777777777778


In [52]:
# Dada a matriz X = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16] ]):
# 3. Faça a soma das colunas:
X = np.array([
     [1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
     [13, 14, 15, 16]])
soma_colunas = np.sum(X, axis=0)
print("\n3. Soma das colunas:")
print(soma_colunas)


3. Soma das colunas:
[28 32 36 40]


In [54]:
#4. Faça a média das linhas
media_linhas = np.mean(X, axis=1)
print("\n4. Média das linhas:")
print(media_linhas)


4. Média das linhas:
[ 2.5  6.5 10.5 14.5]


In [56]:
# 5. Dado o array X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10]) Mostre o elemento de maior valor
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
print("\nElemento de maior valor\n", np.max(X))


Elemento de maior valor
 10


### Aula
-Aula dia 15/01
Exercicios:
1. Crie uma Serie com elementos A, B, C e com os indexes primeiro, segundo, terceiro
2. Agora mostre o primeiro elemento da Serie anterior
3. Baseado na Serie X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])
              **Transforme** em float
4. Mude a ordem da mesma Serie utilizada no Exercicio 3
5. Organize os valores da Serie X = pd.Series([4,2,5,1,3],
              index=['forth','second','fifth','first','third'])
6. Add 5 para todos os elementos da Serie X = pd.Series([1,2,3,4,5])
7. Crie uma máscara para mostrar somente elementos negativos X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
8. Colete todos os elementos negativos X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])


In [ ]:
#1.

In [ ]:
#2.

In [ ]:
#3.

In [ ]:
#4.

In [ ]:
#5.

In [ ]:
#6.

In [ ]:
#7.

In [ ]:
#8.